'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funzionalità di salvataggio automatico My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("def00000-9c6d-47ed-aaf1-4dda8f2b5c03")>  _
        Public Property DirectSound_DeviceGuid() As Global.System.Guid
            Get
                Return CType(Me("DirectSound_DeviceGuid"),Global.System.Guid)
            End Get
            Set
                Me("DirectSound_DeviceGuid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public Property DirectSound_BufferLen() As Integer
            Get
                Return CType(Me("DirectSound_BufferLen"),Integer)
            End Get
            Set
                Me("DirectSound_BufferLen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("250")>  _
        Public Property DirectSound_PreBufferLen() As Integer
            Get
                Return CType(Me("DirectSound_PreBufferLen"),Integer)
            End Get
            Set
                Me("DirectSound_PreBufferLen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DirectSound_EnableFading() As Boolean
            Get
                Return CType(Me("DirectSound_EnableFading"),Boolean)
            End Get
            Set
                Me("DirectSound_EnableFading") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DSPEqualizer_Enabled() As Boolean
            Get
                Return CType(Me("DSPEqualizer_Enabled"),Boolean)
            End Get
            Set
                Me("DSPEqualizer_Enabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property DSPEqualizer_Gain() As Integer
            Get
                Return CType(Me("DSPEqualizer_Gain"),Integer)
            End Get
            Set
                Me("DSPEqualizer_Gain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DSPEqualizer_30_Gain() As Integer
            Get
                Return CType(Me("DSPEqualizer_30_Gain"),Integer)
            End Get
            Set
                Me("DSPEqualizer_30_Gain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DSPEqualizer_60_Gain() As Integer
            Get
                Return CType(Me("DSPEqualizer_60_Gain"),Integer)
            End Get
            Set
                Me("DSPEqualizer_60_Gain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DSPEqualizer_125_Gain() As Integer
            Get
                Return CType(Me("DSPEqualizer_125_Gain"),Integer)
            End Get
            Set
                Me("DSPEqualizer_125_Gain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DSPEqualizer_250_Gain() As Integer
            Get
                Return CType(Me("DSPEqualizer_250_Gain"),Integer)
            End Get
            Set
                Me("DSPEqualizer_250_Gain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DSPEqualizer_500_Gain() As Integer
            Get
                Return CType(Me("DSPEqualizer_500_Gain"),Integer)
            End Get
            Set
                Me("DSPEqualizer_500_Gain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DSPEqualizer_1K_Gain() As Integer
            Get
                Return CType(Me("DSPEqualizer_1K_Gain"),Integer)
            End Get
            Set
                Me("DSPEqualizer_1K_Gain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DSPEqualizer_2K_Gain() As Integer
            Get
                Return CType(Me("DSPEqualizer_2K_Gain"),Integer)
            End Get
            Set
                Me("DSPEqualizer_2K_Gain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DSPEqualizer_4K_Gain() As Integer
            Get
                Return CType(Me("DSPEqualizer_4K_Gain"),Integer)
            End Get
            Set
                Me("DSPEqualizer_4K_Gain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DSPEqualizer_8K_Gain() As Integer
            Get
                Return CType(Me("DSPEqualizer_8K_Gain"),Integer)
            End Get
            Set
                Me("DSPEqualizer_8K_Gain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DSPEqualizer_16K_Gain() As Integer
            Get
                Return CType(Me("DSPEqualizer_16K_Gain"),Integer)
            End Get
            Set
                Me("DSPEqualizer_16K_Gain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LAME_Target() As Integer
            Get
                Return CType(Me("LAME_Target"),Integer)
            End Get
            Set
                Me("LAME_Target") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property LAME_EncoderQualityIndex() As Integer
            Get
                Return CType(Me("LAME_EncoderQualityIndex"),Integer)
            End Get
            Set
                Me("LAME_EncoderQualityIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LAME_ForceCBR() As Boolean
            Get
                Return CType(Me("LAME_ForceCBR"),Boolean)
            End Get
            Set
                Me("LAME_ForceCBR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192")>  _
        Public Property LAME_Bitrate() As Integer
            Get
                Return CType(Me("LAME_Bitrate"),Integer)
            End Get
            Set
                Me("LAME_Bitrate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property LAME_VBRQuality() As Integer
            Get
                Return CType(Me("LAME_VBRQuality"),Integer)
            End Get
            Set
                Me("LAME_VBRQuality") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LAME_VBRModeIndex() As Integer
            Get
                Return CType(Me("LAME_VBRModeIndex"),Integer)
            End Get
            Set
                Me("LAME_VBRModeIndex") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AMPlayerDS.My.MySettings
            Get
                Return Global.AMPlayerDS.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
